#!/bin/bash
file=$1
echo "
set terminal png size 1024,768 enhanced font '/usr/share/fonts/liberation/LiberationSans-Regular.ttf' 12
set output '${file}.png'
set title 'Tiempos de respuesta';
set xlabel 'n de accesos';
set ylabel 'ns';
set log y;
plot \"${file}\" using 1:2 title 'local' w lines,\
\"\" using 1:3 title 'udp' w lines,\
\"\" using 1:4 title 'tcp' w lines
"|gnuplot -persist
